### ISSUE TITLE
README Node.js version requirements are outdated

### ISSUE THREAD

**Issue by forceofseth** [domenic/worm-scraper#64]
When I try to run the scraper with the script "worm-scraper"the script crashes at 97%, I am running node 20.10.0:

`Downloading 304 remaining HTML pages
 ███████████████████████████████████████░ 97% |  53 s | 297/304TypeError: termid
    at Fetch.onAborted (node:internal/deps/undici/undici:10300:53)
    at Fetch.emit (node:events:514:28)
    at Fetch.terminate (node:internal/deps/undici/undici:9487:14)
    at Object.onError (node:internal/deps/undici/undici:10418:38)
    at _Request.onError (node:internal/deps/undici/undici:6587:31)
    at errorRequest (node:internal/deps/undici/undici:9151:17)
    at TLSSocket.onSocketClose (node:internal/deps/undici/undici:8304:9)
    at TLSSocket.emit (node:events:526:35)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7)`
 
If i try to rerun the script i get the followin output:
`Cache contains 304/304 HTML pages

TypeError: URL.parse is not a function
    at isCanonicalizedURL (/opt/javascript/ncanode/20.10.0/node/lib/node_modules/worm-scraper/lib/convert.js:229:14)
    at parseSubstitutions (/opt/javascript/ncanode/20.10.0/node/lib/node_modules/worm-scraper/lib/convert.js:132:14)
    at module.exports (/opt/javascript/ncanode/20.10.0/node/lib/node_modules/worm-scraper/lib/convert.js:24:25)
    at async /opt/javascript/ncanode/20.10.0/node/lib/node_modules/worm-scraper/lib/worm-scraper.js:95:5
    at async /opt/javascript/ncanode/20.10.0/node/lib/node_modules/worm-scraper/lib/worm-scraper.js:127:7`

**Comment by domenic** [comment]
Please upgrade to a modern Node version! As the README explains,

> First you'll need a modern version of [Node.js](https://nodejs.org/en/). The earliest version tested is v20.16.0.

**Comment by domenic** [comment]
Although it looks like 22.1.0 or higher might actually be required these days; I can update the README to explain that.

**Comment by forceofseth** [comment]
worked with node 22.14.0 thanks for the help

**Comment by sergeykad** [comment]
I am getting the following error with Node v24.4.0

```
Cache contains 0/304 HTML pages
Downloading 304 remaining HTML pages
All HTML pages downloaded in 108.6 seconds

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at module.exports (C:\scoop\persist\nodejs\bin\node_modules\worm-scraper\lib\convert.js:17:33)
    at async C:\scoop\persist\nodejs\bin\node_modules\worm-scraper\lib\worm-scraper.js:95:5
    at async C:\scoop\persist\nodejs\bin\node_modules\worm-scraper\lib\worm-scraper.js:127:7
```
